- name: Install and configure Incus and its whole stack
  hosts: all
  order: shuffle
  gather_facts: true
  gather_subset:
    - "default_ipv4"
    - "default_ipv6"
    - "distribution_release"
  any_errors_fatal: true
  vars:
    config_root_dir: "{{ '.' | ansible.builtin.realpath }}"
    ansible_user: ansible
    ansible_become: yes
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3
  roles:
#   - role: system_settings
### - role: netplan
###   when: ansible_distribution in ("Ubuntu", "Debian")
#   - role: ntp
### - role: nvme
    - role: ceph
### - role: linstor
###   when: ansible_distribution == "Ubuntu" and ansible_distribution_version in ("22.04", "24.04")
### - role: lvmcluster
#   - role: ovn
#     when: ansible_distribution in ("Ubuntu", "Debian")
#   - role: incus
